package com.dbcheck.app.domain.noise

object NoiseAlertPolicy {
    const val EXPOSURE_DURATION_MINUTES = 30
    const val EXPOSURE_DURATION_MS = EXPOSURE_DURATION_MINUTES * 60_000L
    const val PEAK_WARNING_DB = 120f
    const val EXPOSURE_DOSE_ALERT_PERCENT = 100f
    const val PROJECTED_DOSE_ALERT_PERCENT = 100f
    const val ALERT_RETRY_COOLDOWN_MINUTES = 30
    const val ALERT_RETRY_COOLDOWN_MS = ALERT_RETRY_COOLDOWN_MINUTES * 60_000L
}
