package com.dbcheck.app.ui.theme

import androidx.compose.ui.graphics.Color

// Dark palette
val DarkBackground = Color(0xFF0E0E0E)
val DarkSurface = Color(0xFF131313)
val DarkSurfaceContainer = Color(0xFF1A1A1A)
val DarkSurfaceContainerHigh = Color(0xFF201F1F)
val DarkSurfaceContainerHighest = Color(0xFF262626)
val DarkSurfaceContainerLowest = Color(0xFF000000)
val DarkOnSurface = Color(0xFFE8E4E0)
val DarkOnSurfaceVariant = Color(0xFFADAAAA)
val DarkPrimary = Color(0xFFC5FE00)
val DarkPrimaryDim = Color(0xFFB9EF00)
val DarkPrimaryContainer = Color(0xFFC5FE00)
val DarkOnPrimaryContainer = Color(0xFF1A2600)
val DarkSecondary = Color(0xFFDFEC60)
val DarkTertiary = Color(0xFF5F5F5F)
val DarkTertiaryFixedDim = Color(0xFF2A2A2A)
val DarkOutlineVariant = Color(0xFFAFB2B3)
val DarkError = Color(0xFFF87171)
val DarkWarning = Color(0xFFFBBF24)
val DarkSuccess = Color(0xFF4ADE80)

// Light palette
val LightBackground = Color(0xFFF9F9F9)
val LightSurface = Color(0xFFF3F4F4)
val LightSurfaceContainer = Color(0xFFECEEEE)
val LightSurfaceContainerHigh = Color(0xFFE0E3E4)
val LightSurfaceContainerHighest = Color(0xFFD8DBDC)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF2F3334)
val LightOnSurfaceVariant = Color(0xFF5C6060)
val LightPrimary = Color(0xFF466906)
val LightPrimaryDim = Color(0xFF5A8A0A)
val LightPrimaryContainer = Color(0xFFD4F5A0)
val LightOnPrimaryContainer = Color(0xFF1A2600)
val LightSecondary = Color(0xFF954B00)
val LightTertiary = Color(0xFF5F5F5F)
val LightTertiaryFixedDim = Color(0xFFF3F0F0)
val LightOutlineVariant = Color(0xFFAFB2B3)
val LightError = Color(0xFFBA1A1A)
val LightWarning = Color(0xFFCC7700)
val LightSuccess = Color(0xFF2D7A2D)
