package com.dbcheck.app.ui.theme

import androidx.compose.ui.graphics.Color

// Dark palette
val DarkBackground = Color(0xFF080808)
val DarkSurface = Color(0xFF101010)
val DarkSurfaceContainer = Color(0xFF171717)
val DarkSurfaceContainerHigh = Color(0xFF202020)
val DarkSurfaceContainerHighest = Color(0xFF2A2A2A)
val DarkSurfaceContainerLowest = Color(0xFF000000)
val DarkOnSurface = Color(0xFFF5F5F5)
val DarkOnSurfaceVariant = Color(0xFFB8B8B8)
val DarkPrimary = Color(0xFFF7F7F7)
val DarkPrimaryDim = Color(0xFFCFCFCF)
val DarkPrimaryContainer = Color(0xFFEDEDED)
val DarkOnPrimaryContainer = Color(0xFF080808)
val DarkSecondary = Color(0xFF8F8F8F)
val DarkTertiary = Color(0xFF5E5E5E)
val DarkTertiaryFixedDim = Color(0xFF242424)
val DarkOutlineVariant = Color(0xFF8C8C8C)
val DarkError = Color(0xFFE07A7A)
val DarkWarning = Color(0xFFC9A24D)
val DarkSuccess = Color(0xFF8EA58E)

// Light palette
val LightBackground = Color(0xFFFAFAFA)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceContainer = Color(0xFFF0F0EF)
val LightSurfaceContainerHigh = Color(0xFFE6E6E3)
val LightSurfaceContainerHighest = Color(0xFFDADAD7)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF111111)
val LightOnSurfaceVariant = Color(0xFF5F5F5F)
val LightPrimary = Color(0xFF111111)
val LightPrimaryDim = Color(0xFF4A4A4A)
val LightPrimaryContainer = Color(0xFFE4E4E1)
val LightOnPrimaryContainer = Color(0xFF111111)
val LightSecondary = Color(0xFF6E6E6E)
val LightTertiary = Color(0xFF8A8A86)
val LightTertiaryFixedDim = Color(0xFFF2F2F0)
val LightOutlineVariant = Color(0xFF8E8E8A)
val LightError = Color(0xFFB45F5F)
val LightWarning = Color(0xFF9A7A33)
val LightSuccess = Color(0xFF607460)
