name: Qodana

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  qodana:
    name: Qodana Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@89eb4357efd2b52e639f3216e63edaf33b82622b
        env:
          QODANA_TOKEN: ${{ github.event_name != 'pull_request' && secrets.QODANA_TOKEN || '' }}
