name: Security Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 8 * * 1'

permissions:
  contents: read

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    container:
      image: semgrep/semgrep:1.162.0@sha256:9349edbadf90c3f3c0c3f55867625354e89680e6fa10d9034042af52fdb0e0d0
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - run: semgrep scan --config auto --sarif --output semgrep.sarif
        env:
          SEMGREP_RULES: p/kotlin p/owasp-top-ten
      - uses: github/codeql-action/upload-sarif@7c1e4cf0b20d7c1872b26569c00ba908797a59bf
        if: always()
        with:
          sarif_file: semgrep.sarif
          category: semgrep

  dependency-check:
    name: OWASP Dependency-Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@1e54355a8b4c8abaa8cc7d0b70aa655a3bb15a6c
        with:
          project: ${{ github.repository }}
          path: '.'
          format: 'SARIF'
          args: >
            --enableExperimental
      - uses: github/codeql-action/upload-sarif@7c1e4cf0b20d7c1872b26569c00ba908797a59bf
        if: always()
        with:
          sarif_file: reports/dependency-check-report.sarif
          category: owasp-dependency-check
